package com.example.vpn

data class ServerInfo(
    val country: String,
    val city: String,
    val flag: String,
    val code: String,
    val basePing: Int,
    val isPremium: Boolean,
    val baseLoad: Int
)

object ServerList {
    val servers = listOf(
        ServerInfo("Auto Detect", "Smart Edge Server", "⚡", "AUTO", 15, false, 28),
        ServerInfo("United States", "New York", "🇺🇸", "US_NY", 45, false, 42),
        ServerInfo("United States", "San Francisco", "🇺🇸", "US_SF", 38, true, 58),
        ServerInfo("United Kingdom", "London", "🇬🇧", "GB", 32, false, 55),
        ServerInfo("Singapore", "Singapore", "🇸🇬", "SG", 18, false, 64),
        ServerInfo("Bangladesh", "Dhaka", "🇧🇩", "BD", 12, false, 35),
        ServerInfo("India", "Mumbai", "🇮🇳", "IN", 22, false, 50),
        ServerInfo("India", "Bangalore", "🇮🇳", "IN_BLR", 25, true, 40),
        ServerInfo("Germany", "Frankfurt", "🇩🇪", "DE", 28, false, 48),
        ServerInfo("Japan", "Tokyo", "🇯🇵", "JP", 35, false, 61),
        ServerInfo("Australia", "Sydney", "🇦🇺", "AU", 48, true, 33),
        ServerInfo("Canada", "Toronto", "🇨🇦", "CA", 42, false, 39),
        ServerInfo("France", "Paris", "🇫🇷", "FR", 29, false, 52),
        ServerInfo("United Arab Emirates", "Dubai", "🇦🇪", "AE", 26, true, 44),
        ServerInfo("Saudi Arabia", "Riyadh", "🇸🇦", "SA", 30, true, 31),
        ServerInfo("Brazil", "São Paulo", "🇧🇷", "BR", 55, true, 47),
        ServerInfo("South Africa", "Cape Town", "🇿🇦", "ZA", 62, true, 25),
        ServerInfo("Netherlands", "Amsterdam", "🇳🇱", "NL", 31, false, 49),
        ServerInfo("Switzerland", "Zurich", "🇨🇭", "CH", 33, true, 18),
        ServerInfo("South Korea", "Seoul", "🇰🇷", "KR", 34, false, 59),
        ServerInfo("Malaysia", "Kuala Lumpur", "🇲🇾", "MY", 20, false, 41),
        ServerInfo("Thailand", "Bangkok", "🇹🇭", "TH", 24, false, 45),
        ServerInfo("Indonesia", "Jakarta", "🇮🇩", "ID", 22, false, 53),
        ServerInfo("Vietnam", "Hanoi", "🇻🇳", "VN", 27, true, 38),
        ServerInfo("Pakistan", "Karachi", "🇵🇰", "PK", 29, false, 47),
        ServerInfo("Italy", "Milan", "🇮🇹", "IT", 34, false, 43),
        ServerInfo("Spain", "Madrid", "🇪🇸", "ES", 36, false, 41),
        ServerInfo("Sweden", "Stockholm", "🇸🇪", "SE", 38, true, 29),
        ServerInfo("Norway", "Oslo", "🇳🇴", "NO", 40, true, 22),
        ServerInfo("Finland", "Helsinki", "🇫🇮", "FI", 41, true, 26),
        ServerInfo("Hong Kong", "Hong Kong", "🇭🇰", "HK", 21, true, 60),
        ServerInfo("Taiwan", "Taipei", "🇹🇼", "TW", 32, true, 54),
        ServerInfo("Turkey", "Istanbul", "🇹🇷", "TR", 39, false, 48),
        ServerInfo("Egypt", "Cairo", "🇪🇬", "EG", 44, true, 34),
        ServerInfo("Qatar", "Doha", "🇶🇦", "QA", 28, true, 36),
        ServerInfo("Kuwait", "Kuwait City", "🇰🇼", "KW", 31, true, 28),
        ServerInfo("New Zealand", "Auckland", "🇳🇿", "NZ", 58, true, 30),
        ServerInfo("Mexico", "Mexico City", "🇲🇽", "MX", 52, false, 37),
        ServerInfo("Argentina", "Buenos Aires", "🇦🇷", "AR", 68, true, 32),
        ServerInfo("Chile", "Santiago", "🇨🇱", "CL", 64, true, 27),
        ServerInfo("Colombia", "Bogota", "🇨🇴", "CO", 59, true, 29),
        ServerInfo("Ireland", "Dublin", "🇮🇪", "IE", 36, false, 35),
        ServerInfo("Belgium", "Brussels", "🇧🇪", "BE", 32, false, 33),
        ServerInfo("Austria", "Vienna", "🇦🇹", "AT", 34, false, 36),
        ServerInfo("Poland", "Warsaw", "🇵🇱", "PL", 37, false, 42),
        ServerInfo("Ukraine", "Kyiv", "🇺🇦", "UA", 42, true, 19),
        ServerInfo("Czech Republic", "Prague", "🇨🇿", "CZ", 35, false, 31),
        ServerInfo("Greece", "Athens", "🇬🇷", "GR", 41, true, 24),
        ServerInfo("Portugal", "Lisbon", "🇵🇹", "PT", 38, true, 28),
        ServerInfo("Singapore", "Changi Edge", "🇸🇬", "SG_PREM", 16, true, 40),
        ServerInfo("Bangladesh", "Chittagong", "🇧🇩", "BD_CTG", 15, true, 25),
        ServerInfo("Iceland", "Reykjavik", "🇮🇸", "IS", 49, true, 12),
        ServerInfo("Japan", "Osaka", "🇯🇵", "JP_OSA", 37, true, 45)
    )
}
